name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}
    strategy:
      matrix:
        gemfile: [gemfiles/activesupport_5.2.gemfile, gemfiles/activesupport_6.0.gemfile]
        ruby: ["2.5", "2.6", "2.7"]
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: RuboCop
      run: bundle exec rubocop

    - name: Tests
      run: bundle exec rake test

    - name: Specs
      run: bundle exec rspec
